version: '3.7'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  nodejs:
    build:
      context: .
    container_name: node
    depends_on:
      - redis
    ports:
      - "3000:3000"
