version: '3.7'

services:
  redis:
    image: redis
    container_name: redis

  nodejs:
    build:
      context: .
    container_name: node
    depends_on:
      - redis
    ports:
      - "80:3000"
